let alfabeto = "ABCDEFGHIJKL";
console.log(alfabeto.length);
let frutas = "Maçã, Banana, Coco";
console.log(frutas.slice(5,12));
let frutas2 = "Maçã, Banana, Coco";
console.log(frutas2.substring(5,12));
let letras = "ABCDE";
console.log(letras.toLowerCase());
let letras2 = "abcde";
console.log(letras2.toUpperCase());